/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.payrollsystem.UI.AddRecord;

/**
 *
 * @author Aid
 */
public class AddRecordPosition extends javax.swing.JFrame {

    /**
     * Creates new form AddRecordPosition
     */
    public AddRecordPosition() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();
        positionNameText = new javax.swing.JLabel();
        positionNameTextField = new javax.swing.JTextField();
        isTeachingField = new javax.swing.JCheckBox();
        positionPayRateText = new javax.swing.JLabel();
        positionPayRateTextField = new javax.swing.JTextField();
        positionRequiredHoursText = new javax.swing.JLabel();
        positionRequiredHoursTextField = new javax.swing.JTextField();
        addPositionButon = new javax.swing.JButton();

        setTitle("Add Position Record");
        setPreferredSize(new java.awt.Dimension(500, 300));

        container.setBackground(new java.awt.Color(38, 38, 38));
        container.setPreferredSize(new java.awt.Dimension(500, 400));

        positionNameText.setForeground(new java.awt.Color(242, 242, 242));
        positionNameText.setText("Name:");

        positionNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                positionNameTextFieldActionPerformed(evt);
            }
        });

        isTeachingField.setText("Teaching Profession");
        isTeachingField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isTeachingFieldActionPerformed(evt);
            }
        });

        positionPayRateText.setForeground(new java.awt.Color(242, 242, 242));
        positionPayRateText.setText("Pay rate:");

        positionPayRateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                positionPayRateTextFieldActionPerformed(evt);
            }
        });

        positionRequiredHoursText.setForeground(new java.awt.Color(242, 242, 242));
        positionRequiredHoursText.setText("Required hours:");

        positionRequiredHoursTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                positionRequiredHoursTextFieldActionPerformed(evt);
            }
        });

        addPositionButon.setText("Add Position");
        addPositionButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPositionButonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(positionNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(positionNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(addPositionButon)
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, containerLayout.createSequentialGroup()
                                .addComponent(positionRequiredHoursText)
                                .addGap(18, 18, 18)
                                .addComponent(positionRequiredHoursTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(containerLayout.createSequentialGroup()
                                .addComponent(positionPayRateText)
                                .addGap(18, 18, 18)
                                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(isTeachingField)
                                    .addComponent(positionPayRateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(positionNameText)
                    .addComponent(positionNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(isTeachingField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(positionPayRateText)
                    .addComponent(positionPayRateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(positionRequiredHoursTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(positionRequiredHoursText))
                .addGap(26, 26, 26)
                .addComponent(addPositionButon)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        getContentPane().add(container, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void positionRequiredHoursTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_positionRequiredHoursTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_positionRequiredHoursTextFieldActionPerformed

    private void positionPayRateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_positionPayRateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_positionPayRateTextFieldActionPerformed

    private void addPositionButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPositionButonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addPositionButonActionPerformed

    private void isTeachingFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isTeachingFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isTeachingFieldActionPerformed

    private void positionNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_positionNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_positionNameTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddRecordPosition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddRecordPosition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddRecordPosition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddRecordPosition.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddRecordPosition().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPositionButon;
    private javax.swing.JPanel container;
    private javax.swing.JCheckBox isTeachingField;
    private javax.swing.JLabel positionNameText;
    private javax.swing.JTextField positionNameTextField;
    private javax.swing.JLabel positionPayRateText;
    private javax.swing.JTextField positionPayRateTextField;
    private javax.swing.JLabel positionRequiredHoursText;
    private javax.swing.JTextField positionRequiredHoursTextField;
    // End of variables declaration//GEN-END:variables
}
